
\ The following words are implemented internally:
\
\ BIN CLOSE-FILE CREATE-FILE DELETE-FILE FILE-POSITION FILE-SIZE INCLUDE-FILE
\ INCLUDED OPEN-FILE R/O R/W READ-FILE READ-LINE REPOSITION-FILE RESIZE-FILE
\ W/O WRITE-FILE WRITE-LINE

.( ... end of file.f ) cr